apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sales-streams.fullname" . }}
  labels:
    {{- include "sales-streams.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-
    quarkus.kafka-streams.bootstrap-servers={{ .Values.kafka.bootstrapServer }}
    {{ if .Values.kafka.securityProtocol -}}
    quarkus.kafka-streams.security.protocol={{ .Values.kafka.securityProtocol }}
    {{ end -}}
    {{ if .Values.kafka.saslMechanism -}}
    quarkus.kafka-streams.sasl.mechanism={{ .Values.kafka.saslMechanism }}
    {{ end -}}
    {{ if eq .Values.kafka.saslMechanism "PLAIN" -}}
    quarkus.kafka-streams.sasl.jaas-config=org.apache.kafka.common.security.plain.PlainLoginModule required \
      username="{{ .Values.kafka.userId }}" \
      password="{{ .Values.kafka.password }}" ;
    {{- end }}

    quarkus.kafka-streams.topics={{ .Values.kafka.streams.topics }}

    quarkus.kafka-streams.application-id={{ .Values.kafka.streams.applicationId }}

    quarkus.kafka-streams.commit.interval.ms={{ .Values.kafka.streams.commitIntervalMs }}
    
    quarkus.kafka-streams.replication.factor={{ .Values.kafka.streams.replicationFactor }}

    topic.sale-change-event={{ .Values.kafka.topics.saleChangeEvent }}
    topic.lineitem-change-event={{ .Values.kafka.topics.lineItemChangeEvent }}
    topic.aggregated-sale={{ .Values.kafka.topics.aggregatedSale }}
  
