apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cashback-service.fullname" . }}
  labels:
    {{- include "cashback-service.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-
    mp.messaging.connector.smallrye-kafka.bootstrap.servers={{ .Values.kafka.bootstrapServer }}
    mp.messaging.incoming.expense.topic={{ .Values.kafka.topics.expenses }}
    mp.messaging.incoming.expense.group.id={{ .Values.kafka.consumerGroup }}
    
    {{- if .Values.kafka.securityProtocol -}}
    mp.messaging.connector.smallrye-kafka.security.protocol={{ .Values.kafka.securityProtocol }}
    {{ end -}}
    {{- if .Values.kafka.saslMechanism -}}
    mp.messaging.connector.smallrye-kafka.sasl.mechanism={{ .Values.kafka.saslMechanism }}
    {{ end -}}
    {{- if eq .Values.kafka.saslMechanism "PLAIN" -}}
    mp.messaging.connector.smallrye-kafka.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
      username="{{ .Values.kafka.userId }}" \
      password="{{ .Values.kafka.password }}" ;
    {{- end }}

    quarkus.datasource.username={{ .Values.postgresql.username }}
    quarkus.datasource.password={{ .Values.postgresql.password }}
    quarkus.datasource.jdbc.url=jdbc:postgresql://{{ .Values.postgresql.host }}:5432/{{ .Values.postgresql.database }}
