nameOverride: "kafka"

kafka:
  version: 3.6.0
  cluster:
    replicas: 2
  zookeeper:
    replicas: 3
  config:
    autoCreateTopics: false
    defaultReplicationFactor: 2
    offsetsTopicReplicationFactor: 2
    transactionStateLogReplicationFactor: 2
    transactionStateLogMinIsr: 2
    minInsyncReplicas: 1
    interBrokerProtocolVersion: '3.6' 

argocd:
  enabled: false
  syncwave: "-2"
